---
new_page_extension: md
auto_deploy: false
admin_path: "/"
webhook_url: 
sections:
  podcasts:
    default_front_matter_template: podcasts
  contacto:
    default_front_matter_template: contacto
  acerca:
    default_front_matter_template: acerca
  blog:
    default_front_matter_template: blog
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:filename:"
version: 0.18.1
