---
upload_path: "/static/img/:year:/:month:/"
frontmatter_file_url_template: "/:year:/:month:/"
body_file_url_template: "/img/:year:/:month:/"
new_page_extension: md
auto_deploy: true
admin_path: "/"
webhook_url: 
sections:
  podcasts:
    default_front_matter_template: podcasts
  contacto:
    default_front_matter_template: contacto
  acerca:
    default_front_matter_template: acerca
  blog:
    default_front_matter_template: blog
version: 0.18.1
