---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/acerca
  label: Acerca
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/contacto
  label: Contacto
  create: all
  match: "**/*"
- type: directory
  path: content/podcasts
  label: Podcasts
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:filename:"
version: 0.18.1
