---
new_page_extension: md
auto_deploy: false
admin_path: "/"
webhook_url: 
sections:
- path: content/blog
  label: Blog
  create: all
  default_front_matter_template: blog
- path: content/acerca
  label: Acerca
  create: all
  default_front_matter_template: acerca
- path: content
  label: Pages
  create: all
  default_front_matter_template: page
- path: content/contacto
  label: Contacto
  create: all
  default_front_matter_template: contacto
- path: content/podcasts
  label: Podcasts
  create: all
  default_front_matter_template: podcasts
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:filename:"
version: 0.18.1
